### ISSUE TITLE
Masthead like tumblr for all contributors and staff

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#18]

**Comment by mayarichman** [comment]
@IsabelleNastasia  Do we want it to look a lot like the tumblr but with circles instead of squares for images? How often are we adding new contributors?

**Comment by IsabelleNastasia** [comment]
I wonder if we should keep the masthead just for the staff? not sure how
often contributors are included in a masthead (especially since we have
contributors with their own "pages"). what say you?

On Thu, Nov 14, 2013 at 5:16 PM, Maya notifications@github.com wrote:

> @IsabelleNastasia https://github.com/IsabelleNastasia Do we want it to
> look a lot like the tumblr but with circles instead of squares for images?
> How often are we adding new contributors?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/18#issuecomment-28528499
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by IsabelleNastasia** [comment]
To answer your question (sorry I'm super space-y): I think it would
basically be the same as Tumblr with the circles instead of squares. If
there is a way to make it more pretty thats cool too!

On Thu, Nov 14, 2013 at 5:18 PM, Isabelle Nastasia <
isabelle.nastasia@gmail.com> wrote:

> I wonder if we should keep the masthead just for the staff? not sure how
> often contributors are included in a masthead (especially since we have
> contributors with their own "pages"). what say you?
> 
> On Thu, Nov 14, 2013 at 5:16 PM, Maya notifications@github.com wrote:
> 
> > @IsabelleNastasia https://github.com/IsabelleNastasia Do we want it to
> > look a lot like the tumblr but with circles instead of squares for images?
> > How often are we adding new contributors?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/18#issuecomment-28528499
> > .
> 
> ## 
> 
> Isabelle Nastasia
> PGP: She/her/hers
> Cofounder/Managing Editor - youngist.org
> Communications Strategy - New York Students Rising (NYSR)
> Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
> 917 608 2747

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by IsabelleNastasia** [comment]
Just got my answer: http://www.thenation.com/masthead --- Mastheads are
usually super stripped down, maybe we should just make ours a list of the
staff and what we do?

On Thu, Nov 14, 2013 at 5:19 PM, Isabelle Nastasia <
isabelle.nastasia@gmail.com> wrote:

> To answer your question (sorry I'm super space-y): I think it would
> basically be the same as Tumblr with the circles instead of squares. If
> there is a way to make it more pretty thats cool too!
> 
> On Thu, Nov 14, 2013 at 5:18 PM, Isabelle Nastasia <
> isabelle.nastasia@gmail.com> wrote:
> 
> > I wonder if we should keep the masthead just for the staff? not sure how
> > often contributors are included in a masthead (especially since we have
> > contributors with their own "pages"). what say you?
> > 
> > On Thu, Nov 14, 2013 at 5:16 PM, Maya notifications@github.com wrote:
> > 
> > > @IsabelleNastasia https://github.com/IsabelleNastasia Do we want it
> > > to look a lot like the tumblr but with circles instead of squares for
> > > images? How often are we adding new contributors?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/18#issuecomment-28528499
> > > .
> > 
> > ## 
> > 
> > Isabelle Nastasia
> > PGP: She/her/hers
> > Cofounder/Managing Editor - youngist.org
> > Communications Strategy - New York Students Rising (NYSR)
> > Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
> > 917 608 2747
> 
> ## 
> 
> Isabelle Nastasia
> PGP: She/her/hers
> Cofounder/Managing Editor - youngist.org
> Communications Strategy - New York Students Rising (NYSR)
> Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
> 917 608 2747

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
Perfecto!

**Comment by mayarichman** [comment]
Basically done. http://youngist.github.io/clean-blog/masthead/
Only staff is listed. Need to make sure all links are there and working. Closing.

**Comment by IsabelleNastasia** [comment]
+1
